
<div id="order_history_block">
    <?php  echo "++++++";?>
<?php if ($this->canAddComment()):?>
<div id="history_form" class="order-history-form">
<div><?php echo Mage::helper('sales')->__('Add Order Comments') ?></div>
<span class="field-row">
<label class="normal" for="history_status"><?php echo Mage::helper('sales')->__('Status') ?></label><br/>
<select name="history[status]" class="select" id="history_status">
<?php foreach ($this->getStatuses() as $_code=>$_label): ?>
<option value="<?php echo $_code ?>"<?php if($_code==$this->getOrder()->getStatus()): ?> selected="selected"<?php endif; ?>><?php echo $_label ?></option>
<?php endforeach; ?>
</select>
</span>
<span class="field-row">
<label class="normal" for="history_comment"><?php echo Mage::helper('sales')->__('Comment') ?></label>
<textarea name="history[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"></textarea>
</span>
<div class="f-left">
<?php if ($this->canSendCommentEmail()): ?>
<input name="history[is_customer_notified]" type="checkbox" id="history_notify" value="1" /><label class="normal" for="history_notify"> <?php echo Mage::helper('sales')->__('Notify Customer by Email') ?></label><br />
<?php endif; ?>
<input name="history[is_visible_on_front]" type="checkbox" id="history_visible" value="1" /><label class="normal" for="history_visible"> <?php echo Mage::helper('sales')->__('Visible on Frontend') ?></label>
</div>
<div class="f-right">
<?php echo $this->getChildHtml('submit_button') ?>
</div>
<div class="clear"></div>
</div>
<div class="divider"></div>
<?php endif;?>
<ul class="note-list">
<?php //echo  '<pre>';
$getbilling_address_data = $this->getOrder()->getBillingAddress();
$countryName = Mage::getModel('directory/country')->load($getbilling_address_data['country_id'])->getName(); //get country name from country code

$getbilling_address = array($getbilling_address_data['prefix'],$getbilling_address_data['firstname'],$getbilling_address_data['lastname'],$getbilling_address_data['company']
,$getbilling_address_data['street'],$getbilling_address_data['city'],$getbilling_address_data['postcode'],$getbilling_address_data['region']
,$countryName,$getbilling_address_data['telephone'],$getbilling_address_data['fax']);


$getbilling_array = array_filter($getbilling_address); 


?>
<?php $i=0;foreach ($this->getOrder()->getStatusHistoryCollection(true) as $_item): $i++;?>
    
<?php  if($i==2)
{
    $commentpart1 = array_filter(explode(",",$_item['comment'])); 
}

?>
    
    
<?php   $commentpart = array_filter(explode(",",$_item['comment'])); 
?>
<li>
<strong><?php echo $this->helper('core')->formatDate($_item->getCreatedAtDate(), 'medium') ?></strong>
<?php  
$user = Mage::getSingleton('admin/session');  //get admin information
$userUsername = $user->getUser()->getUsername(); //get username  of admin user
?>      
<?php echo $this->helper('core')->formatTime($_item->getCreatedAtDate(), 'medium') ?><span class="separator">|</span><strong><?php echo $_item->getStatusLabel() ?></strong><br/>

<small><?php echo $this->helper('sales')->__('Admin User: ') ?><strong class="subdue"><span style="font-weight:bold"><?php echo  $userUsername;   ?></span></strong></small>
<br>
<small>
<?php echo $this->helper('sales')->__('Customer') ?>
<strong class="subdue">
<?php if ($this->isCustomerNotificationNotApplicable($_item)): ?>
<?php echo $this->helper('sales')->__('Notification Not Applicable') ?>
<?php elseif ($
<?php else: ?>
<?php echo $this->helper('sales')->__('Not Notified') ?>
<?php endif; ?>
</strong></small>
<?php if ($_item->getComment()): ?>

<?php 

 echo $_item->getComment();array('b','br','strong','i','u') ?>
<?php endif; ?>
</li>
<?php endforeach; ?>
</ul>

</div>

